# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/vaibhavi
spring.datasource.username=root
spring.datasource.password=lokesh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server configuration
# 0 = dynamic port, will pick a free port automatically
server.port=9090

# DevTools configuration
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true